spring:
  application:
    name: CookBook2


  datasource:
    url: jdbc:postgresql://localhost:5440/Recipe
    driver-class-name: org.postgresql.Driver
    username: cookbook_dev2
    password: cookbook_dev12
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
