CREATE TABLE recipe
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    ingredients VARCHAR(255),
    rating      DOUBLE PRECISION,
    times_made  INTEGER,
    last_change TIMESTAMP WITHOUT TIME ZONE,
    favorite    BOOLEAN,
    CONSTRAINT pk_recipe PRIMARY KEY (id)
);

CREATE TABLE recipe_meal_types
(
    recipe_id BIGINT NOT NULL,
    meal_type VARCHAR(255)
);

ALTER TABLE recipe_meal_types
    ADD CONSTRAINT fk_recipe_meal_types_on_recipe FOREIGN KEY (recipe_id) REFERENCES recipe (id);