CREATE TABLE image
(
    image_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    img_url   VARCHAR(255),
    recipe_fk BIGINT                                  NOT NULL,
    CONSTRAINT pk_image PRIMARY KEY (image_id)
);

CREATE TABLE meal_type_mapping_table
(
    meal_type_id BIGINT NOT NULL,
    recipe_fk_id    BIGINT NOT NULL,
    CONSTRAINT pk_meal_type PRIMARY KEY (meal_type_id, recipe_fk_id)
);

CREATE TABLE meal_types
(
    meal_id BIGINT       NOT NULL,
    meal    VARCHAR(255) NOT NULL,
    CONSTRAINT pk_meal_types PRIMARY KEY (meal_id)
);

CREATE TABLE recipe
(
    recipe_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recipe_title       VARCHAR(255),
    recipe_ingredients VARCHAR(255),
    recipe_directions  VARCHAR(255),
    recipe_rating      DOUBLE PRECISION,
    recipe_last_change TIMESTAMP WITHOUT TIME ZONE,
    recipe_favorite    BOOLEAN,
    CONSTRAINT pk_recipe PRIMARY KEY (recipe_id)
);

ALTER TABLE image
    ADD CONSTRAINT FK_IMAGE_ON_RECIPE_FK FOREIGN KEY (recipe_fk) REFERENCES recipe (recipe_id);

ALTER TABLE meal_type_mapping_table
    ADD CONSTRAINT fk_meal_type_on_meal_type FOREIGN KEY (meal_type_id) REFERENCES meal_types (meal_id);

ALTER TABLE meal_type_mapping_table
    ADD CONSTRAINT fk_meal_type_on_recipe FOREIGN KEY (recipe_fk_id) REFERENCES recipe (recipe_id);